import React from 'react'
import Head from 'next/head'
import Header from 'src/components/header'
import Footer from 'src/components/footer'

import fetchLocalData from 'src/utils/fetchLocalData'

export default Child => class App extends React.Component {
	static async getInitialProps(ctx) {
		// Retrieve props that will be used app wise
		const {	locale } = ctx.query
		const localData = await fetchLocalData(locale, `{
			settings(q: "order=-sys.createdAt&limit=1"){
				locale
				languageName
				basename
				availableLocales
				storeUrl
				logo { url }
			}

			contentTypeSlugs(q: "order=-sys.createdAt&limit=1"){
				lessonPlan
				lessonPlanCollection
				lessonPlanGroup
				definition
				material
				page
			}

			textStrings(q: "order=-sys.createdAt&limit=1"){
				content
				home
				searchLessonPlans
				more
				author
				duration
				classSize
				groupSize
				overview
				materials
				shop
				modifications
				learningObjectives
				nationalStandards
				teachingAssessment
				preparation
				lessonSteps
				vocabulary
				attachments
				saveAsPrintableFile
				download
				relatedLessons
				nextLesson
				all
				previousLesson
				foundLessons
				noLessonsFound
				ageGroup
				coMaterial
				tag
				lessonPlan
				lessonPlanCollection
				companyAddress
				copyrightNotice
			}
		}`)
		const settings = localData.settings.shift()
		const strings = localData.textStrings.shift()
		const contentTypeSlugs = localData.contentTypeSlugs.shift()

		settings.currentLocale = {
			locale       : settings.locale,
			languageName : settings.languageName,
			basename     : settings.basename ? settings.basename : ''
		}
		settings.availableLocales = settings.availableLocales.map(line => {
			const array = line.split('_')
			return {
				locale       : array[0],
				languageName : array[1],
				basename     : array[2] ? array[2] : ''
			}
		})
		delete settings.locale
		delete settings.languageName
		delete settings.basename

		const appProps = {
			settings,
			contentTypeSlugs,
			strings
		}
		// Retrive props of the current page
		const pageProps = await Child.getInitialProps(ctx, fetchLocalData, appProps)
		return {
			appProps,
			...pageProps
		}
	}

	render() {
		return (
			<div className='root app'>
				<style jsx>{`
					/* This stylesheet generated by Transfonter (https://transfonter.org) on August 4, 2017 2:45 PM */
					@font-face { font-family: 'Brandon Text'; src: url('/static/fonts/BrandonText-Medium.eot'); src: url('/static/fonts/BrandonText-Medium.eot?#iefix') format('embedded-opentype'),url('/static/fonts/BrandonText-Medium.woff2') format('woff2'),url('/static/fonts/BrandonText-Medium.woff') format('woff'),url('/static/fonts/BrandonText-Medium.ttf') format('truetype'); font-weight: 500; font-style: normal; }
					@font-face { font-family: 'Brandon Text'; src: url('/static/fonts/BrandonText-Regular.eot');	src: url('/static/fonts/BrandonText-Regular.eot?#iefix') format('embedded-opentype'),url('/static/fonts/BrandonText-Regular.woff2') format('woff2'),url('/static/fonts/BrandonText-Regular.woff') format('woff'),url('/static/fonts/BrandonText-Regular.ttf') format('truetype'); font-weight: normal; font-style: normal; }
					@font-face { font-family: 'Brandon Text'; src: url('/static/fonts/BrandonText-Bold.eot'); src: url('/static/fonts/BrandonText-Bold.eot?#iefix') format('embedded-opentype'),url('/static/fonts/BrandonText-Bold.woff2') format('woff2'),url('/static/fonts/BrandonText-Bold.woff') format('woff'),url('/static/fonts/BrandonText-Bold.ttf') format('truetype'); font-weight: bold; font-style: normal; }

					:global(body) {
						margin: 0;
						font-family: 'Brandon Text', sans-serif;
						font-size: 16px;
					}
					:global(*){
						box-sizing: border-box;
					}
				`}</style>
				<Head>
					<link rel="stylesheet" href="/static/lib/carousel.min.css"/>
				</Head>
				<Header {...this.props}/>
				<Child {...this.props} />
				<Footer {...this.props}/>
			</div>
		)
	}
}
